# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# See https://circleci.com/docs/2.0/configuration-reference/ for configuration reference.
version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:8.12.0
    steps:
      # [task:advanced]: Add caching of npm packages here
      - checkout
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Build"
          command: yarn build
      - run:
          name: "Run tests"
          command: yarn test

workflows:
  version: 2
  test-and-build:
    jobs:
      - build
      # [task:advanced]: Add automatic deployment to Heroku here
